# -*- coding: utf-8 -*-
"""RAG_Banao_Tech

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1unV3sPCi8vbShIMuIbfgqaWMIFj2HfDo

**RAG PIPELINE - QUIZ GENERATION**
"""

pip install langchain-text-splitters

#import and install
!pip install pypdf chromadb sentence-transformers --quiet

from pypdf import PdfReader
from sentence_transformers import SentenceTransformer
import chromadb
from transformers import pipeline

pip install langchain-community

from pypdf import PdfReader

def load_pdfs(pdf_paths):
    """
    pdf_paths: list of PDF file paths
    returns: combined text from all PDFs
    """
    full_text = ""

    for path in pdf_paths:
        reader = PdfReader(path)
        for page in reader.pages:
            page_text = page.extract_text()
            if page_text:
                full_text += page_text + "\n"

    return full_text

#CHUNK THE DATA
def chunk_text(text, chunk_size=450,overlap=80):
    words = text.split()
    chunks = []

    step=chunk_size - overlap

    for i in range(0, len(words), step):
        chunks.append(" ".join(words[i:i+chunk_size]))
    return chunks

#improved chunking
from langchain_text_splitters import RecursiveCharacterTextSplitter

def chunk_text(text,chunk_size=500,overlap=90):
  text_splitter= RecursiveCharacterTextSplitter(
      chunk_size=chunk_size,
      chunk_overlap=overlap,
      separators=["\n\n", "\n", " ", ""]
  )
  chunks=text_splitter.split_text(text)
  return chunks

# EMBEDDING MODEL
embedder = SentenceTransformer("all-mpnet-base-v2")

#CREATE VECTOR DATABASE
client = chromadb.Client()
collection = client.get_or_create_collection(
    name="rag_collection",
    metadata={"hnsw:space": "cosine"}) #required in new api

#clear previous collection
def clear_collection():
   data = collection.get()
   ids = data.get("ids", [])
   if ids:   # only delete if not empty
      collection.delete(ids=ids)
      print(f"Deleted {len(ids)} old vectors.")
   else:
       print("Collection already empty.")

#Add chunks to vector DB
def add_to_chroma(chunks):
    ids = [f"doc_{i}" for i in range(len(chunks))]
    embeddings = embedder.encode(chunks, convert_to_numpy=True).tolist()

    collection.add(
        ids=ids,
        embeddings=embeddings,
        documents=chunks
    )

def ingest_all_pdfs_from_dir(pdf_dir="data/pdfs"):
    import os
    pdf_paths = [
        os.path.join(pdf_dir, f)
        for f in os.listdir(pdf_dir)
        if f.lower().endswith(".pdf")
    ]

    if not pdf_paths:
        print("No PDFs found for RAG ingestion.")
        return

    print("Ingesting PDFs for RAG...")
    text = load_pdfs(pdf_paths)
    chunks = chunk_text(text)
    clear_collection()
    add_to_chroma(chunks)
    print("RAG ingestion complete.")

#Retrieve top-k chunks (basic)
def retrieve(query, k=5):
    query_emb = embedder.encode([query], convert_to_numpy=True).tolist()

    results = collection.query(
        query_embeddings=query_emb,
        n_results=k
    )
    return results["documents"][0]

"""**ADDING RERANKING LAYER FOR BETTER PERFORMANCE**"""

!pip install rank_bm25

from rank_bm25 import BM25Okapi

def rerank_bm25(query, chunks, top_n=5):
    tokenized_chunks = [chunk.lower().split() for chunk in chunks]
    bm25 = BM25Okapi(tokenized_chunks)
    scores = bm25.get_scores(query.lower().split())

    ranked = sorted(zip(scores, chunks), reverse=True)
    return [chunk for _, chunk in ranked[:top_n]]

def retrieve_with_rerank(topic, top_k=8):
    dense_chunks = retrieve(topic, k=top_k)
    reranked_chunks = rerank_bm25(topic, dense_chunks)
    return reranked_chunks

from transformers import pipeline

llm = pipeline(
    "text2text-generation",
    model="google/flan-t5-large",
    max_new_tokens=500,
    temperature=0.3
)

def trim_context(text, max_words=120):
    return " ".join(text.split()[:max_words])


def generate_quiz_with_context(topic, difficulty):
    chunks = retrieve_with_rerank(
        f"important academic concepts, processes, and examples related to {topic}"
    )

    question_types = [
        "concept understanding",
        "application-based reasoning",
        "cause and effect",
        "comparison",
        "example-based inference"
    ]

    questions = []

    for i, chunk in enumerate(chunks, start=1):
        chunk = trim_context(chunk)
        qtype = question_types[(i - 1) % len(question_types)]

        prompt = f"""
You are a university-level exam paper setter.

Create ONE {difficulty}-level MCQ.

QUESTION TYPE:
{qtype}

STRICT RULES:
- Use ONLY the given context
- Academic tone
- No negative framing
- No repetition
- MUST include 4 options
- MUST include correct answer

CONTEXT:
{chunk}

FORMAT (STRICT):
Q{i}. <question>
A. <option>
B. <option>
C. <option>
D. <option>
Answer: <A/B/C/D>
"""

        output = llm(prompt)[0]["generated_text"].strip()
        questions.append(output)

    return "\n\n".join(questions)

def run_rag_pipeline(pdf_paths, topic="General", difficulty="easy"):
    print("Loading PDFs...")
    text = load_pdfs(pdf_paths)


    print("Chunking text...")
    chunks = chunk_text(text)

    print("Resetting vector DB...")
    clear_collection()

    print("Adding chunks...")
    add_to_chroma(chunks)

    print("Generating quiz...")
    quiz = generate_quiz_with_context(topic, difficulty)

    print("\n===== QUIZ =====\n")
    print(quiz)
    return quiz

run_rag_pipeline(
    [
        "/content/50 page sample PDF.indd.pdf",
        "/content/biology_sample.pdf"
    ],
    topic="Biology",
    difficulty="easy"
)

# ================================
# RAG EVALUATION METRICS MODULE
# ================================

from typing import List, Dict

# --------------------------------
# 1. RETRIEVAL METRICS
# --------------------------------

def concept_coverage_score(
    retrieved_chunks: List[str],
    key_concepts: List[str]
) -> float:
    """
    Measures how many important concepts appear
    in retrieved chunks.
    """
    found = set()
    for concept in key_concepts:
        for chunk in retrieved_chunks:
            if concept.lower() in chunk.lower():
                found.add(concept.lower())
                break
    return len(found) / len(key_concepts) if key_concepts else 0.0


def retrieval_precision(
    retrieved_chunks: List[str],
    topic_keywords: List[str]
) -> float:
    """
    Measures how many retrieved chunks are relevant.
    """
    relevant = 0
    for chunk in retrieved_chunks:
        if any(kw.lower() in chunk.lower() for kw in topic_keywords):
            relevant += 1
    return relevant / len(retrieved_chunks) if retrieved_chunks else 0.0


# --------------------------------
# 2. CONTEXT QUALITY
# --------------------------------

def evaluate_context_quality(llm, context_chunks: List[str]) -> Dict:
    """
    LLM-as-a-Judge for context relevance, completeness, noise.
    """
    context = "\n".join(context_chunks)

    prompt = f"""
You are evaluating retrieved context for quiz generation.

Rate the following from 1 (poor) to 5 (excellent):

1. Relevance to topic
2. Completeness of information
3. Noise level (5 = very clean, no irrelevant info)

Context:
{context}

Return JSON only with keys:
relevance, completeness, noise
"""

    response = llm(prompt)[0]["generated_text"]
    return response


# --------------------------------
# 3. QUESTION QUALITY
# --------------------------------

def evaluate_question_quality(llm, context_chunks: List[str], quiz_text: str) -> Dict:
    """
    Evaluates answerability, groundedness, clarity, constraints.
    """
    context = "\n".join(context_chunks)

    prompt = f"""
You are evaluating MCQs generated by a RAG system.

Context:
{context}

Generated Questions:
{quiz_text}

Rate from 1 (poor) to 5 (excellent):

1. Answerability from context
2. Groundedness (no hallucination)
3. Clarity and academic tone
4. Constraint adherence (MCQ format, 4 options, one answer)
5. Difficulty alignment

Return JSON only with keys:
answerability, groundedness, clarity, constraints, difficulty
"""

    response = llm(prompt)[0]["generated_text"]
    return response


# --------------------------------
# 4. FULL RAG EVALUATION RUNNER
# --------------------------------

def run_rag_evaluation(
    llm,
    topic: str,
    retrieved_chunks: List[str],
    quiz_text: str,
    key_concepts: List[str],
    topic_keywords: List[str]
):
    """
    Runs full evaluation pipeline and prints results.
    """

    print("\n===== RAG EVALUATION REPORT =====\n")

    # Retrieval metrics
    coverage = concept_coverage_score(retrieved_chunks, key_concepts)
    precision = retrieval_precision(retrieved_chunks, topic_keywords)

    print("🔹 Retrieval Metrics")
    print(f"Concept Coverage Score: {coverage:.2f}")
    print(f"Retrieval Precision: {precision:.2f}\n")

    # Context metrics
    print("🔹 Context Quality (LLM Judge)")
    context_eval = evaluate_context_quality(llm, retrieved_chunks)
    print(context_eval, "\n")

    # Question metrics
    print("🔹 Question Quality (LLM Judge)")
    question_eval = evaluate_question_quality(llm, retrieved_chunks, quiz_text)
    print(question_eval, "\n")

    print("===== END OF REPORT =====\n")

retrieved_chunks = retrieve_with_rerank("Biology")
quiz = generate_quiz_with_context("Biology", "easy")

run_rag_evaluation(
    llm=llm,
    topic="Biology",
    retrieved_chunks=retrieved_chunks,
    quiz_text=quiz,
    key_concepts=["cell", "photosynthesis", "chlorophyll", "ATP"],
    topic_keywords=["cell", "energy", "reaction"]
)

def is_question_valid(llm, context, question_text):
    """
    Returns 1 if question is valid, else 0
    """
    prompt = f"""
Check if the following MCQ is VALID.

Rules:
- Must be answerable ONLY from context
- Must NOT use outside knowledge
- Must have 4 options (A-D)
- Must include one correct answer

Context:
{context}

Question:
{question_text}

Reply ONLY with:
VALID or INVALID
"""

    output = llm(prompt)
    verdict = output[0]["generated_text"].strip().upper()

    if "VALID" in verdict:
        return 1
    return 0

def generation_precision(llm, context_chunks, quiz_text):
    """
    Calculates precision for generated questions
    """
    context = " ".join(context_chunks[:2])  # keep context short

    # Split questions roughly
    questions = quiz_text.split("\n\n")

    valid_count = 0

    for q in questions:
        if len(q.strip()) < 50:
            continue

        valid = is_question_valid(llm, context, q)
        valid_count += valid

    total = len(questions)

    if total == 0:
        return 0.0

    return round(valid_count / total, 2)

precision = generation_precision(llm, retrieved_chunks, quiz)

print("\n🔹 GENERATION PRECISION")
print("Question Precision:", precision)